


def var_err():
    a = 1
    b = 2
    print(a)
    print(b)
    return

var_err()

#this will be error as you can't access the local variable outside the function
#print(a)